name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4  # <-- ATUALIZADO
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with: # Usar 'with' é mais comum para passar parâmetros que 'env'
          USERNAME: alefsantos498
          # A linha do GITHUB_TOKEN não é mais necessária aqui
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
